FROM python:3.9-slim

WORKDIR /3tier-app/backend

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --upgrade pip

COPY app.py .

COPY static ./static

COPY templates ./templates

EXPOSE 5001

CMD ["python", "app.py"]
